# Generated by Django 3.2.5 on 2021-07-21 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('uploadDateTime', models.DateTimeField(default=datetime.datetime(2021, 7, 21, 11, 6, 3, 391663))),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
